### ISSUE TITLE
How do I get proposal in .json format？

### ISSUE THREAD

**Issue by Elaineok** [chuchienshu/ultra-thin-PRM#3]
![image](https://user-images.githubusercontent.com/46559128/63992715-d0433180-cb1f-11e9-92e3-bae2e01cd321.png)

**Comment by chuchienshu** [comment]
https://github.com/chuchienshu/ultra-thin-PRM/blob/81f44ac0c4cb79f629ce19b71514832d097bb0da/main.py#L45
